# Generated by Django 4.0.6 on 2022-07-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0002_alter_celebrity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrity',
            options={'ordering': ['-created'], 'verbose_name': 'Celebrity', 'verbose_name_plural': 'Celebrities'},
        ),
    ]
